// app/dashboard/business/[id]/page.tsx
import type { Metadata } from "next";
import { getCurrentUser } from "@/lib/supabase/server";
import { BusinessProfileClient } from "../BusinessProfileClient";

export const metadata: Metadata = { title: "Edit business profile", robots: { index: false, follow: false } };

export default async function EditBusinessProfilePage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const [{ id }, user] = await Promise.all([params, getCurrentUser()]);
  // The id is generated by the list page, so an unknown id means "create this one".
  return <BusinessProfileClient profileId={id} authenticated={Boolean(user)} />;
}
